### ISSUE TITLE
Lista de competências de cada membro evolvido no projeto. 

### ISSUE THREAD

**Issue by tallysdev** [tallysdev/eventSync#26]
# Substitua sua competência anterior com uma nova nos comentarios da issue
Antes: 

    Membro     |     Competências   |
    ---------  | ----------- |
    Italo Maurício      | Desenvolvedor Java
    Lucas Mateus        | Desenvolvedor Python
    Vinicius Maia       | Desenvolvedor TypeScript
    Tallys Aureliano | git, javascript, typescript, node, flutter, vue, canva, gerencia de requisitos, gerencia de atividades, mediação de conflitos |
    Dayanne Xavier      | Desenvolvedor C

Exemplo de resposta: 
Tallys Aureliano | git, javascript, typescript, node, flutter, vue, canva, gerencia de requisitos, gerencia de atividades, mediação de conflitos |
------- | -------- |

**Comment by DayXL** [comment]
Dayanne Xavier      | C, javascript, flutter, canva, Python
